// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CHeader: typeof import('./components/CHeader/index.vue')['default']
    CHeaderInner: typeof import('./components/CHeaderInner/index.vue')['default']
    CLayout: typeof import('./components/CLayout/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFiles: typeof import('~icons/ep/files')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
  }
}

export { }
